// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_ICQdePxk6oVX6nLMyqLBb8kibKdiKzw',
    appId: '1:619402315386:web:7e2fea35937efc6c575dc3',
    messagingSenderId: '619402315386',
    projectId: 'gradegen-c2781',
    authDomain: 'gradegen-c2781.firebaseapp.com',
    storageBucket: 'gradegen-c2781.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3wufVZI1MvtMn1r95a91dUtYlehcMX8k',
    appId: '1:619402315386:android:fac203e2177bea27575dc3',
    messagingSenderId: '619402315386',
    projectId: 'gradegen-c2781',
    storageBucket: 'gradegen-c2781.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhokxJ4ZraAyHCDjSShDIfsxLRyAd5n_8',
    appId: '1:619402315386:ios:bd392416144c3955575dc3',
    messagingSenderId: '619402315386',
    projectId: 'gradegen-c2781',
    storageBucket: 'gradegen-c2781.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhokxJ4ZraAyHCDjSShDIfsxLRyAd5n_8',
    appId: '1:619402315386:ios:bd392416144c3955575dc3',
    messagingSenderId: '619402315386',
    projectId: 'gradegen-c2781',
    storageBucket: 'gradegen-c2781.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_ICQdePxk6oVX6nLMyqLBb8kibKdiKzw',
    appId: '1:619402315386:web:4be92cd5992bd3fd575dc3',
    messagingSenderId: '619402315386',
    projectId: 'gradegen-c2781',
    authDomain: 'gradegen-c2781.firebaseapp.com',
    storageBucket: 'gradegen-c2781.firebasestorage.app',
  );
}
